
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ARJAY
 */
public class Coverter extends javax.swing.JFrame {

    /**
     * Creates new form Coverter
     */
    public Coverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        txtfrom = new javax.swing.JComboBox<>();
        txtto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Enter the Amount");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("From");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("To");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));
        jPanel1.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 69, 185, -1));

        txtfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR", "INR", "LKR", "PHP", "USD", " ", " " }));
        jPanel1.add(txtfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 107, 185, -1));

        txtto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR", "INR", "LKR", "PHP", "USD", " ", " ", " ", " " }));
        jPanel1.add(txtto, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 145, 185, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 248, 84, 35));

        exit.setBackground(new java.awt.Color(153, 153, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 248, 84, 35));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 248, 84, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -150, 620, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double tot;
        
        Double amount = Double.parseDouble(txtamount.getText());
        
        if (txtfrom.getSelectedItem().toString()== "USD" && txtto.getSelectedItem().toString() =="LKR") 
        {
        tot = amount * 187.09;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₨ " + tot.toString());
        }
       else if (txtfrom.getSelectedItem().toString()== "USD" && txtto.getSelectedItem().toString() =="INR") 
        {
        tot = amount * 73.54;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₹ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "USD" && txtto.getSelectedItem().toString() =="PHP") 
        {
        tot = amount * 48.06;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₱ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "USD" && txtto.getSelectedItem().toString() =="EUR") 
        {
        tot = amount * 0.82;
            JOptionPane.showMessageDialog(this,"Your Amount will be € " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "USD" && txtto.getSelectedItem().toString() =="USD") 
        {
        tot = amount * 1;
            JOptionPane.showMessageDialog(this,"Your Amount will be $ " + tot.toString());
        }
        if (txtfrom.getSelectedItem().toString()== "PHP" && txtto.getSelectedItem().toString() =="LKR") 
        {
        tot = amount * 3.89;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₨ " + tot.toString());
        }
       else if (txtfrom.getSelectedItem().toString()== "PHP" && txtto.getSelectedItem().toString() =="INR") 
        {
        tot = amount * 1.53;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₹ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "PHP" && txtto.getSelectedItem().toString() =="PHP") 
        {
        tot = amount * 1;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₱ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "PHP" && txtto.getSelectedItem().toString() =="EUR") 
        {
        tot = amount * 0.017;
            JOptionPane.showMessageDialog(this,"Your Amount will be € " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "PHP" && txtto.getSelectedItem().toString() =="USD") 
        {
        tot = amount * 0.021;
            JOptionPane.showMessageDialog(this,"Your Amount will be $ " + tot.toString());
        }
         if (txtfrom.getSelectedItem().toString()== "EUR" && txtto.getSelectedItem().toString() =="LKR") 
        {
        tot = amount * 227.41;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₨ " + tot.toString());
        }
       else if (txtfrom.getSelectedItem().toString()== "EUR" && txtto.getSelectedItem().toString() =="INR") 
        {
        tot = amount * 89.38;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₹ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "EUR" && txtto.getSelectedItem().toString() =="PHP") 
        {
        tot = amount * 58.41;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₱ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "EUR" && txtto.getSelectedItem().toString() =="EUR") 
        {
        tot = amount * 1;
            JOptionPane.showMessageDialog(this,"Your Amount will be € " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "EUR" && txtto.getSelectedItem().toString() =="USD") 
        {
        tot = amount * 1.22;
            JOptionPane.showMessageDialog(this,"Your Amount will be $ " + tot.toString());
        }
           if (txtfrom.getSelectedItem().toString()== "LKR" && txtto.getSelectedItem().toString() =="LKR") 
        {
        tot = amount * 1;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₨ " + tot.toString());
        }
       else if (txtfrom.getSelectedItem().toString()== "LKR" && txtto.getSelectedItem().toString() =="INR") 
        {
        tot = amount * 0.39;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₹ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "LKR" && txtto.getSelectedItem().toString() =="PHP") 
        {
        tot = amount * 0.26;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₱ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "LKR" && txtto.getSelectedItem().toString() =="EUR") 
        {
        tot = amount * 0.0044;
            JOptionPane.showMessageDialog(this,"Your Amount will be € " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "LKR" && txtto.getSelectedItem().toString() =="USD") 
        {
        tot = amount * 0.0053;
            JOptionPane.showMessageDialog(this,"Your Amount will be $ " + tot.toString());
        }
           if (txtfrom.getSelectedItem().toString()== "INR" && txtto.getSelectedItem().toString() =="LKR") 
        {
        tot = amount * 2.54;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₨ " + tot.toString());
        }
       else if (txtfrom.getSelectedItem().toString()== "INR" && txtto.getSelectedItem().toString() =="INR") 
        {
        tot = amount * 1;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₹ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "INR" && txtto.getSelectedItem().toString() =="PHP") 
        {
        tot = amount * 0.65;
            JOptionPane.showMessageDialog(this,"Your Amount will be ₱ " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "INR" && txtto.getSelectedItem().toString() =="EUR") 
        {
        tot = amount * 0.011;
            JOptionPane.showMessageDialog(this,"Your Amount will be € " + tot.toString());
        }
        else if (txtfrom.getSelectedItem().toString()== "INR" && txtto.getSelectedItem().toString() =="USD") 
        {
        tot = amount * 0.014;
            JOptionPane.showMessageDialog(this,"Your Amount will be $ " + tot.toString());
        }






            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to exit","Select",JOptionPane.YES_NO_OPTION);
        if (a==0) 
        {
        System.exit(0);
        }    
        
    }//GEN-LAST:event_exitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtamount.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JComboBox<String> txtfrom;
    private javax.swing.JComboBox<String> txtto;
    // End of variables declaration//GEN-END:variables
}
